CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <>''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <>''), 
    done BOOLEAN,
    projectsId INTEGER REFERENCES projects(id)
);

INSERT INTO projects(name,priority,description,deliverydate)
VALUES ('make a web App',1,'Using Javascript','2019-05-12')

INSERT INTO projects(name,priority,description,deliverydate)
VALUES ('make an App',1,'Using dart','2019-05-13')

INSERT INTO projects(name,priority,description,deliverydate)
VALUES ('make a desktop App',2,'Using C++','2019-05-14')

--INSERT TASKS DATA
INSERT INTO tasks(name,done,projectsId)
VALUES('donwload vuejs',false, 1);